Creating Tensor

In [1]:
import torch 
print(torch.__version__)

2.12.0+cpu


In [2]:
if torch.cuda.is_available():
    print("Gpu is available") 
    print(f"Device name {torch.cude.get_device_name(0)}")

In [3]:
a = torch.empty(2,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [4]:
type(a)

torch.Tensor

In [5]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
torch.rand(2,3)

tensor([[0.1558, 0.3699, 0.7345],
        [0.5400, 0.9325, 0.7300]])

In [8]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [9]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [11]:
torch.arange(1,20,2)

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [12]:
torch.linspace(1,10,10)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [13]:
x = torch.tensor([[1,2,3],[4,5,6]]) 
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
x.shape

torch.Size([2, 3])

In [15]:
torch.empty_like(x)

tensor([[3340947883952,             0,             0],
        [            0,             0,             0]])

In [16]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [21]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Data type

In [22]:
x.dtype

torch.int64

In [23]:
torch.tensor([1.0,2.0,3.0,4.0],dtype=torch.int32)

tensor([1, 2, 3, 4], dtype=torch.int32)

In [24]:
torch.tensor([1.0,2.0,3.0,4.0],dtype=torch.float32)

tensor([1., 2., 3., 4.])

In [27]:
x = x.to(torch.float32)

In [28]:
x.dtype

torch.float32

# Scaler operation 

In [30]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [31]:
x+2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [32]:
x-2

tensor([[-1,  0,  1],
        [ 2,  3,  4]])

In [33]:
x * 2

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

In [34]:
x / 2

tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])

In [37]:
#floor 
x = x *100

In [38]:
x //3

tensor([[ 33,  66, 100],
        [133, 166, 200]])

In [39]:
x % 2

tensor([[0, 0, 0],
        [0, 0, 0]])