Creating Tensor

In [1]:
import torch 
print(torch.__version__)

2.12.0+cpu


In [2]:
if torch.cuda.is_available():
    print("Gpu is available") 
    print(f"Device name {torch.cude.get_device_name(0)}")

In [3]:
a = torch.empty(2,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [4]:
type(a)

torch.Tensor

In [5]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
torch.rand(2,3)

tensor([[0.3915, 0.4043, 0.1462],
        [0.6175, 0.8427, 0.6418]])

In [8]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [9]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [11]:
torch.arange(1,20,2)

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [12]:
torch.linspace(1,10,10)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [13]:
x = torch.tensor([[1,2,3],[4,5,6]]) 
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
x.shape

torch.Size([2, 3])

In [15]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [16]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [18]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Data type

In [19]:
x.dtype

torch.int64

In [20]:
torch.tensor([1.0,2.0,3.0,4.0],dtype=torch.int32)

tensor([1, 2, 3, 4], dtype=torch.int32)

In [21]:
torch.tensor([1.0,2.0,3.0,4.0],dtype=torch.float32)

tensor([1., 2., 3., 4.])

In [22]:
x = x.to(torch.float32)

In [23]:
x.dtype

torch.float32

# Scaler operation 

In [24]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [25]:
x+2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [26]:
x-2

tensor([[-1,  0,  1],
        [ 2,  3,  4]])

In [27]:
x * 2

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

In [28]:
x / 2

tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])

In [29]:
#floor 
x = x *100

In [30]:
x //3

tensor([[ 33,  66, 100],
        [133, 166, 200]])

In [31]:
x % 2

tensor([[0, 0, 0],
        [0, 0, 0]])

# Element Wise operation

In [32]:
a = torch.rand(2,3)
b = torch.rand(2,3)

In [33]:
a

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [34]:
a + b

tensor([[0.9357, 1.0899, 0.5967],
        [1.7253, 1.5526, 1.7335]])

In [35]:
a - b

tensor([[ 0.4879,  0.4852,  0.2399],
        [ 0.0776,  0.4411, -0.2205]])

In [36]:
a * b

tensor([[0.1594, 0.2381, 0.0746],
        [0.7426, 0.5540, 0.7391]])

In [37]:
a / b

tensor([[3.1790, 2.6049, 2.3445],
        [1.0942, 1.7938, 0.7743]])

In [38]:
a**b

tensor([[0.9267, 0.9303, 0.8560],
        [0.9180, 0.9983, 0.7614]])

In [39]:
a%b

tensor([[0.0401, 0.1829, 0.0615],
        [0.0776, 0.4411, 0.7565]])

In [40]:
c = torch.tensor([-1,-4,-7,-8])

In [41]:
torch.abs(c)

tensor([1, 4, 7, 8])

In [42]:
c = torch.tensor([1,4,7,8])

In [43]:
torch.neg(c)

tensor([-1, -4, -7, -8])

In [44]:
d = torch.tensor([1.4,4.6,7.4,8.7])

In [45]:
torch.round(d)

tensor([1., 5., 7., 9.])

In [46]:
torch.ceil(d)

tensor([2., 5., 8., 9.])

In [47]:
d = torch.tensor([100,200,300,400])

In [48]:
torch.clamp(d, min=1,max=2)

tensor([2, 2, 2, 2])

# Reduction Operation

In [49]:
e = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)

In [50]:
e

tensor([[0., 1., 9.],
        [9., 8., 0.]])

In [51]:
torch.mean(e)

tensor(4.5000)

In [52]:
torch.sum(e)

tensor(27.)

In [53]:
torch.sum(e, dim=0)

tensor([9., 9., 9.])

In [54]:
torch.sum(e, dim=1)

tensor([10., 17.])

In [55]:
torch.mean(e, dim=1)

tensor([3.3333, 5.6667])

In [56]:
torch.median(e)

tensor(1.)

In [57]:
#max and min 
torch.max(e)

tensor(9.)

In [58]:
torch.min(e)

tensor(0.)

In [59]:
torch.prod(e)

tensor(0.)

In [60]:
torch.std(e)

tensor(4.5935)

In [61]:
torch.var(e)


tensor(21.1000)

In [62]:
#argmax, argmean 
torch.argmax(e)

tensor(2)

In [63]:
torch.argmin(e)

tensor(0)

In [64]:
import torch 

In [66]:
f= torch.randint(size=(2,3),low=0,high=10)
g= torch.randint(size=(3,3),low=0,high=10)

In [67]:
torch.matmul(f,g)

tensor([[184, 126, 161],
        [164, 136, 151]])

In [68]:
#dot product 

In [69]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

In [70]:
torch.dot(vector1,vector2)

tensor(11)

In [71]:
f.shape

torch.Size([2, 3])

In [73]:
f

tensor([[5, 9, 9],
        [7, 5, 9]])

In [72]:
torch.transpose(f,0,1)

tensor([[5, 7],
        [9, 5],
        [9, 9]])

In [74]:
h = torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)

In [75]:
h

tensor([[3., 6., 1.],
        [5., 5., 0.],
        [4., 3., 8.]])

In [76]:
torch.det(h)

tensor(-125.0000)

In [77]:
torch.inverse(h)

tensor([[-0.3200,  0.3600,  0.0400],
        [ 0.3200, -0.1600, -0.0400],
        [ 0.0400, -0.1200,  0.1200]])

In [78]:
i = torch.randint(size=(2,3),low=0,high=10)
j = torch.randint(size=(2,3),low=0,high=10)

In [79]:
print(i) 
print(j)

tensor([[8, 3, 3],
        [5, 0, 6]])
tensor([[4, 0, 8],
        [4, 7, 2]])


In [80]:
i > j

tensor([[ True,  True, False],
        [ True, False,  True]])

# special fucntion

In [81]:
k = torch.tensor([10,20,30])
k

tensor([10, 20, 30])

In [82]:
torch.log(k)

tensor([2.3026, 2.9957, 3.4012])

In [83]:
torch.exp(k)

tensor([2.2026e+04, 4.8517e+08, 1.0686e+13])

In [84]:
torch.sqrt(k)

tensor([3.1623, 4.4721, 5.4772])

In [85]:
torch.sigmoid(k)

tensor([1.0000, 1.0000, 1.0000])

In [86]:
torch.softmax(k, dim=0)

NotImplementedError: "softmax_lastdim_kernel_impl" not implemented for 'Long'

In [87]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [89]:
b = a + 5 
b

tensor([6, 7, 8])

In [90]:
m = torch.rand(2,3)
n = torch.rand(2,3)

In [91]:
m.add_(n)

tensor([[1.6384, 0.7776, 0.3072],
        [1.8746, 1.0939, 0.1762]])