# version 1

In [3]:
import torch 
import torch.nn as nn 


In [9]:
class Model(nn.Module):

    def __init__(self,num_features):
        super().__init__() 
        self.linear = nn.Linear(num_features,1)
        self.sigmoid= nn.Sigmoid() 

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out
             

            

# Create datasets

In [10]:
features = torch.rand(10,5)

In [11]:
features

tensor([[0.6380, 0.3728, 0.0517, 0.9649, 0.8102],
        [0.2276, 0.4123, 0.7176, 0.9162, 0.6396],
        [0.1230, 0.0062, 0.6439, 0.3903, 0.3549],
        [0.8432, 0.8810, 0.3520, 0.9326, 0.8535],
        [0.2339, 0.9443, 0.6039, 0.9961, 0.5450],
        [0.6818, 0.7591, 0.6907, 0.6136, 0.5992],
        [0.3761, 0.8365, 0.7939, 0.7160, 0.2433],
        [0.1334, 0.8281, 0.1772, 0.3867, 0.6521],
        [0.6923, 0.2352, 0.1966, 0.2417, 0.0307],
        [0.0656, 0.2891, 0.7051, 0.6308, 0.7817]])

In [12]:
features.shape[1]

5

In [13]:
#Craete model 
model = Model(features.shape[1])

In [15]:
#calling model for forward pass 
# model.forward(features) 

model(features)


tensor([[0.5183],
        [0.4723],
        [0.4722],
        [0.5269],
        [0.4740],
        [0.5042],
        [0.4541],
        [0.5414],
        [0.4801],
        [0.5026]], grad_fn=<SigmoidBackward0>)

In [16]:
#show weights 

model.linear.weight

Parameter containing:
tensor([[ 0.0504,  0.0926, -0.1652, -0.2808,  0.4130]], requires_grad=True)

In [17]:
# visualize 

!pip install torchinfo 

In [18]:
from torchinfo import summary 

summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00